<footer>
    <nav>
        <ul>
            <li>                
                questo
            </li>
            <li>                
                è
            </li>
            <li>                
                il
            </li>
            <li>                
                footer
            </li>
        </ul>
    </nav>
</footer>