<header>
    <nav>
        <ul>
            <li>                
                questo
            </li>
            <li>                
                è
            </li>
            <li>                
                un
            </li>
            <li>                
                header
            </li>
        </ul>
    </nav>
</header>